services:
    forumhulp.htmlemail.listener:
        class: forumhulp\htmlemail\event\listener
        arguments:
            - '@config'
            - '@dispatcher'
        tags:
            - { name: event.listener }
